packaging_format = 2

id = "shlink"
name = "Shlink"
description.en = "Self-hosted URL shortener"
description.fr = "Raccourcisseur d'URL auto-hébergé"

version = "4.2.1~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://shlink.io/"
userdoc = "https://shlink.io/documentation/"
code = "https://github.com/shlinkio/shlink"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.front]
        url = "https://github.com/shlinkio/shlink-web-client/releases/download/v4.1.2/shlink-web-client_4.1.2_dist.zip"
        sha256 = "f704cddb064c6f09c8e11e24a43924bbb5a63e17498d985d3b488611769987bc"
        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/shlinkio/shlink-web-client"
        autoupdate.asset = "^shlink-web-client_.*_dist.zip$"

        [resources.sources.main]
        url = "https://github.com/shlinkio/shlink/releases/download/v4.2.1/shlink4.2.1_php8.2_dist.zip"
        sha256 = "106adbf68d322d6de32bda0a7d1e351e29b1239c9593d75b2fec95b9552f7bf6"
        autoupdate.strategy = "latest_github_release"
        autoupdate.upstream = "https://github.com/shlinkio/shlink"
        autoupdate.asset = "^shlink.*_php8.2_dist.zip$"
        

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "postgresql, php8.2-apcu, php8.2-pgsql, php8.2-gd, php8.2-curl, php8.2-intl, php8.2-gmp, php8.2-xml"

    [resources.database]
    type = "postgresql"
